theme: jekyll-theme-minimal
title: Cactool
description: An easy way to collaboratively code social media posts and visual media for manual content and discourse analysis
logo: /assets/cactool_logo_sq.png
#google_analytics: [Your Google Analytics tracking ID]
