theme: jekyll-theme-minimal
title: Cactool
description: An easy way to collaboratively code social media posts and visual media for manual content and discourse analysis
#google_analytics: [Your Google Analytics tracking ID]
